destination: public
exclude: [Gemfile, Gemfile.lock, .ruby-*, public]

gmaps_api_key: AIzaSyCZyT6gk-tkkZwmlg9zovl2oIol0v1ZXK8
title: "Puerto Rico: Get A Flu Shot"
logo: "http://code4puertorico.org/static/images/logo.svg"
locality: "Puerto Rico"
flu_info_link: http://www.flu.nc.gov/
start_latitude: 18.219592
start_longitude: -66.513350
state: Puerto Rico
api_endpoint: http://brigades.opendatanetwork.com/resource/58zj-bvwz.json
socrata_app_token: HCvAA8iIMxefx6BzUAEQN0wqE
about:
  Developed orginally by [Tom Kompare](http://about.me/tomkompare) in partnership with the [NC Department of Public Health (CDPH)](http://www.cityofchicago.org/city/en/depts/cdph.html). This map application is developed in partnership with [Code for Raleigh](http://www.codeforraleigh.com) and Socrata. 

  [The code behind this web application](https://github.com/socrata/flushots) is free, open, and under a [MIT License](https://github.com/socrata/flushots/blob/master/LICENSE). The data behind the application is a [ Socrata dataset](https://brigades.opendatanetwork.com/HEALTH/North-Carolina-Flu-Shot-Locations/7mef-4h72) hosted on the [Brigade Open Data Sharing Platform.](https://brigades.opendatanetwork.com/)

